config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments do
  	collection do
  		get 'letter_pad'
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def index
  	@comments = Comment.all
  end

  def create
    comment = Comment.create! params.require(:comment).permit(:content)
    comment.image.attach(params[:comment][:image])
    redirect_to comment    
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def letter_pad
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "letter", 
        disposition: 'inline',
        layout: false,
        margin:  {   top: 0,
                     bottom: 0,
                     left: 0,
                     right: 0 }
         # footer:  { html: { template: 'comments/footer.pdf.erb',layout: false } }
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/footer.pdf.erb
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>Footer</title>

    <style>
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box; 
            font-family: "Gotham SSm A", "Gotham SSm B", Helvetica, sans-serif;
            font-size: 14px;
            font-style: normal;
           }


        .invoice-footer{
        	width: 35px;
        	height: 35px;
        	background: #3FA496;
        	/*position*: fixed;*/
        }
        .bold{
        	font-weight: bold;
        }

    </style>
</head>

<body>
<div class="invoice-footer">test</div>

</body>
</html>

app/views/comments/index.html.erb
<h1>Listing comments</h1>
 
<table border="1">
  <tr>
    <th>Content</th>
    <th>Image</th>
    <th></th>
  </tr>
 
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.content %></td>
      <td><%= comment.image %></td>
      <td><%= link_to 'Show', comment_path(comment) %></td>
    </tr>
  <% end %>
</table>

app/views/comments/letter_pad.pdf.erb
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title>HMAN</title>
    <!-- <link rel="stylesheet" type="text/css" href="https://cloud.typography.com/7349534/6023792/css/fonts.css" /> -->

    <style>
        * {
            margin: 0px;
            padding: 0px;
            /*3FA496*/
            box-sizing: border-box; 
            font-family: "Gotham SSm A", "Gotham SSm B", Helvetica, sans-serif;
            font-size: 14px;
            font-style: normal;
           }

		.row::after {
		  content: "";
		  clear: both;
		  display: table;
		}

        .container{width: 100%;height: 1370px;}
        .address{
        	position: absolute;
        	top: 1%;
        	right: 7%;
        	font-size: 14px;
        	line-height: 25px;
        	color: #fff;

        }
        .invoice-footer{
        	width: 100%;
        	height: 35px;
        	background: #3FA496;
        	position: fixed;
        }

        .invoice-body{
        	width: 80%;
        	height: auto;
        	margin: 12%;
        	background: url('file://<%=Rails.root%>/app/assets/images/pdf/hm-bg.png') no-repeat;
        	background-position:  50% 65%;
        	background-size: 40%;
        }
        .column{
        	width: 50%;
        	float: left;
        }
        .padding_bottom_30{
        	padding-bottom: 30px;
        }

        .padding_bottom_40{
        	padding-bottom: 40px;
        }

        .padding_bottom_50{
        	padding-bottom: 50px;
        }

        .padding_bottom_20{
        	padding-bottom: 20px;
        }
        .bold{
        	font-weight: bold;
        }

    </style>
</head>

<body>
<div class="container">
	<div class="row" style="background: #3FA496;">
	   <img src="file://<%=Rails.root%>/app/assets/images/pdf/head.png" width="100%">
	</div>


    <div class="address">
    	<h5 style="font-weight: bold;text-transform: uppercase;">Invictus Realty Private Limited</h5>
    	CIN:U74999KA2017PTC101193 <br>
    	#84, R.V Road, Basavanagudi, Bengaluru-04.<br>
    	+91-9092250522, +91-9980409636 <br>
        www.housingman.com <br> 
        support@housingman.com<br>
    </div>

        <div class="invoice-body">


        	<div style="text-align: center;">
        	<p style="border-bottom: 2px solid black;font-size: 20px;display: inline-block;font-weight: bold;">TO WHOMSOEVER IT MAY CONCERN</p>
            </div> 

        	<div class="row padding_bottom_30" style="padding-top: 30px;">
        		<div class="column">
        			<p><span class="bold">Sub:</span> Experience / Relieving Letter</p>
        		</div>
        		<div class="column" style="text-align: center;">
        			<p><span class="bold">Date:</span> 14.11.2019</p>
        		</div>
        	</div>

           <div class="padding_bottom_30" style="line-height: 28px;">
           	This is to confirm that Testing was employed by us as a Sr.Software Engineer from 05.01.2015 to<br>
           	14.11.2019. He has been relieved from his duties and responsibilities by the end of the business hours<br>
           	on <b>14.11.2019</b> from Invictus Realty Private Limited (Housingman.com).
           </div>

           <p class="padding_bottom_40">We wish him all the best in his future endeavors.</p>
           <p class="padding_bottom_30">Thanking You</p>

           <p class="padding_bottom_50">Regards</p>
           <p class="padding_bottom_50">For Invictus Realty Private Limited</p>

           <p class="padding_bottom_20">Krish Boobathy R</p>
           <p class="padding_bottom_50">HR & Operations</p>

        </div>

</div>
<div class="invoice-footer"></div>


</body>
</html>

app/views/comments/new.html.erb
<%= form_with model: @comment, local: true  do |form| %>
  <%= form.text_area :content %><br><br>
  <%= form.file_field :image%><br>
  <%= form.submit %>
<% end %>

app/views/comments/show.html.erb
View <%= image_tag @comment.image %>
<%= link_to 'Download', rails_blob_path(@comment.image, disposition: "attachment"), :style=>'color:red'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storageapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>